### ISSUE TITLE
parentNode is sometimes undefined

### ISSUE THREAD

**Issue by azmeuk** [mxcod-fr/fabuloos-js#1]
Hi,
In the [replace function](https://github.com/egeny/fabuloos-js/blob/master/src/renderers/FlashRenderer.js#L117), I get the following error `TypeError: element.parentNode is null`.
It seems that there is sometimes this property is not defined : https://developer.mozilla.org/en/docs/DOM/element.parentNode

**Comment by neovov** [comment]
Hi,

Thanks for the feedback.
Could you provide a way to reproduce this issue so we could think of a clean way to fix it?

:beers:
